"""32-byte binary wire protocol for the LOB accelerator.

This module defines the exact byte layout of every UDP payload plus the
``encode_message`` / ``decode_message`` functions used by both the market-data
simulator and the golden reference model. The layout mirrors the FPGA
register map one-to-one (see README for the field-level mapping).

Final wire format (v1, network byte order / big-endian, 32 bytes):

    offset  size  field          type     notes
    0       1     version        uint8    protocol version (0x01)
    1       1     msg_type       uint8    numeric: 0x01 ADD, 0x02 CANCEL,
                                          0x03 MODIFY, 0x04 EXECUTE
    2       1     side           uint8    0x00 BUY, 0x01 SELL
    3       1     flags          uint8    see FLAG_* below
    4       4     seq_num        uint32   monotonically increasing sequence no.
    8       8     order_id       uint64   client order id
    16      4     price          uint32   fixed point, e.g. 10025 == $100.25
    20      4     quantity       uint32   shares / lots
    24      8     timestamp_ns   uint64   nanoseconds

This is the FROZEN protocol shared verbatim by the Python reference model,
the UVM environment, the RTL UDP parser, and the testbench stimulus
generator (see docs/01_protocol_spec.md). Every field is
fixed-width and big-endian, so the RTL can index the payload by byte offset
directly.
"""

import struct
from dataclasses import dataclass

MSG_SIZE = 32
VERSION = 0x01

# Message types (frozen numeric encodings -- byte 1).
MSG_ADD = 0x01
MSG_CANCEL = 0x02
MSG_MODIFY = 0x03
MSG_EXECUTE = 0x04

# Side (frozen numeric encodings -- byte 2).
SIDE_BUY = 0x00
SIDE_SELL = 0x01

# flags bit 0 (byte 3):
#   execution report generated by the matching engine     -> 0
#   external execution (applied to the book as a fill)    -> FLAG_EXTERNAL
FLAG_EXTERNAL = 0x01

# Field offsets -- used by UVM to poke/read individual bytes of a payload.
OFF_VERSION = 0
OFF_MSG_TYPE = 1
OFF_SIDE = 2
OFF_FLAGS = 3
OFF_SEQ_NUM = 4
OFF_ORDER_ID = 8
OFF_PRICE = 16
OFF_QUANTITY = 20
OFF_TIMESTAMP = 24

_VALID_MSG_TYPES = frozenset((MSG_ADD, MSG_CANCEL, MSG_MODIFY, MSG_EXECUTE))
_VALID_SIDES = frozenset((SIDE_BUY, SIDE_SELL))

# Big-endian: version u8, msg_type u8, side u8, flags u8, seq u32,
#             order_id u64, price u32, quantity u32, timestamp u64
_PACKER = struct.Struct(">BBBBIQIIQ")
assert _PACKER.size == MSG_SIZE


@dataclass
class Message:
    """Decoded representation of one wire message.

    Field order matches the wire layout 1:1 so the dataclass and the struct
    packer line up.
    """

    version: int = VERSION
    msg_type: int = MSG_ADD
    side: int = SIDE_BUY
    flags: int = 0
    seq_num: int = 0
    order_id: int = 0
    price: int = 0
    quantity: int = 0
    timestamp_ns: int = 0

    def encode(self) -> bytes:
        """Encode this message into exactly 32 bytes (big-endian)."""
        return encode_message(self)

    @classmethod
    def decode(cls, payload):
        """Decode a 32-byte binary payload into a Message (classmethod)."""
        return decode_message(payload)


def encode_message(msg: Message) -> bytes:
    """Encode a Message into exactly 32 bytes (big-endian)."""
    _validate(msg)
    try:
        return _PACKER.pack(
            msg.version,
            msg.msg_type,
            msg.side,
            msg.flags,
            msg.seq_num,
            msg.order_id,
            msg.price,
            msg.quantity,
            msg.timestamp_ns,
        )
    except struct.error as exc:  # pragma: no cover - defensive
        raise ValueError(f"field does not fit its fixed width: {exc}") from exc


def decode_message(payload) -> Message:
    """Decode a 32-byte UDP payload into a Message.

    Raises ValueError for a wrong-length payload, an unsupported protocol
    version, or an invalid msg_type / side.
    """
    if isinstance(payload, bytearray):
        payload = bytes(payload)
    if len(payload) != MSG_SIZE:
        raise ValueError(
            f"payload must be exactly {MSG_SIZE} bytes, got {len(payload)}"
        )
    msg = Message(*_PACKER.unpack(payload))
    _validate(msg)
    return msg


def build_message(
    msg_type,
    side=SIDE_BUY,
    flags=0,
    seq_num=0,
    order_id=0,
    price=0,
    quantity=0,
    timestamp_ns=0,
):
    """Convenience constructor for a wire Message."""
    return Message(
        VERSION, msg_type, side, flags, seq_num, order_id, price,
        quantity, timestamp_ns,
    )


def hexdump(payload) -> str:
    """Human-readable hex dump of a payload (UVM / debug aid)."""
    if isinstance(payload, bytearray):
        payload = bytes(payload)
    if len(payload) != MSG_SIZE:
        raise ValueError(f"expected {MSG_SIZE} bytes, got {len(payload)}")
    lines = []
    for row in range(0, MSG_SIZE, 8):
        chunk = payload[row : row + 8]
        lines.append(f"{row:02d}  " + " ".join(f"{b:02x}" for b in chunk))
    return "\n".join(lines)


def _validate(msg):
    if msg.version != VERSION:
        raise ValueError(f"unsupported protocol version 0x{msg.version:02x}")
    if msg.msg_type not in _VALID_MSG_TYPES:
        raise ValueError(f"invalid msg_type 0x{msg.msg_type:02x}")
    if msg.side not in _VALID_SIDES:
        raise ValueError(f"invalid side 0x{msg.side:02x}")
