"""Random stress test + golden-reference cross-check for the LOB model.

The requirement: generate 10000 random messages and verify
  * no negative quantity,
  * no duplicated order_id,
  * the order book remains consistent.

The stream is generated by the market-data simulator (exchange side), which
also emits EXECUTE_ORDER reports. The golden reference consumer replays the
same stream through a fresh OrderBook and must reproduce the exchange's book
state exactly, while validating every execution report -- so any divergence
between the exchange and the reference model fails the test.
"""

import unittest

from lob.simulator import OrderFlowGenerator
from lob.consumer import GoldenReference


class TestStress(unittest.TestCase):
    def test_10000_random_messages(self):
        seed = 0xCAFE
        generator = OrderFlowGenerator(seed=seed)
        reference = GoldenReference()

        for index in range(10000):
            for msg in generator.next_batch():
                reference.process_message(msg)
            # Full structural self-check on the reference book at every
            # checkpoint; the exchange book is checked below.
            if index % 100 == 0:
                reference.book.check_invariants()

        generator.book.check_invariants()
        reference.book.check_invariants()

        # 1. no negative / zero quantities anywhere
        for order in reference.book._orders.values():
            self.assertGreater(order.quantity, 0)

        # 2. no duplicated order_id in the book (a set loses nothing)
        self.assertEqual(
            len(reference.book._orders), len(reference.book.order_ids()))

        # 3. book remains consistent: consumer reproduces the exchange exactly
        self.assertEqual(reference.snapshot(), generator.book.snapshot())

        # 4. every matched fill report was validated by the reference
        #    (each trade emits two reports: the buyer's and the seller's)
        self.assertEqual(reference.matched_fills, 2 * generator.stats["trades"])
        self.assertEqual(reference.external_fills, generator.stats["external"])

        # 5. all four message types were exercised, incl. EXECUTE reports
        stats = generator.stats
        self.assertGreater(stats["add"], 0)
        self.assertGreater(stats["cancel"], 0)
        self.assertGreater(stats["modify"], 0)
        self.assertGreater(stats["external"], 0)
        self.assertGreater(stats["execute"], 0)

        # 6. generator's live-order tracking matches the exchange book
        self.assertEqual(set(generator.live), generator.book.order_ids())

    def test_determinism_same_seed(self):
        payloads_a = OrderFlowGenerator(seed=123).run_payloads(500)
        payloads_b = OrderFlowGenerator(seed=123).run_payloads(500)
        self.assertEqual(payloads_a, payloads_b)

    def test_different_seed_differs(self):
        payloads_a = OrderFlowGenerator(seed=123).run_payloads(200)
        payloads_b = OrderFlowGenerator(seed=456).run_payloads(200)
        self.assertNotEqual(payloads_a, payloads_b)

    def test_all_messages_are_exactly_32_bytes(self):
        from lob.protocol import MSG_SIZE, decode_message
        for payload in OrderFlowGenerator(seed=7).run_payloads(200):
            self.assertEqual(len(payload), MSG_SIZE)
            decode_message(payload)  # every message is decodable/valid


if __name__ == "__main__":
    unittest.main()
